<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" sitemap:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap Index</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
					<style type="text/css">body{font-family:"Lucida Grande","Lucida Sans Unicode",Tahoma,Verdana,sans-serif;font-size:13px}#header,#footer{padding:2px;margin:10px 0;font-size:8pt;color:gray}a{color:black}td{font-size:11px;padding: 5px 10px;text-align:center;}th{font-size:12px;padding: 5px 10px;text-align:center;}tr.high{background-color:whitesmoke}.left{text-align:left}</style>
			</head>
			<body>
				<h1>XML Sitemap Index</h1>
				<div id="content">
					<table cellpadding="5">
						<tr class="high">
							<th>#</th>
							<th class="left">Sitemap</th>
							<th>Modified</th>
						</tr>
						<xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
						<xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
						<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
							<tr><xsl:if test="position() mod 2 != 1"><xsl:attribute  name="class">high</xsl:attribute></xsl:if>
								<td><xsl:value-of select="position()"/></td>
								<td class="left"><xsl:variable name="itemURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
									<a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
								</td>
								<td><xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/></td>
							</tr>
						</xsl:for-each>
					</table>
				</div>
				<div id="footer">
					<p>Generated by <a href="https://www.againtheme.com/againcart-sitemap" title="Againcart Smart Sitemap" target="_blank">Againcart Smart Sitemap</a> extension from <a href="https://www.againtheme.com" title="Againtheme" target="_blank">Againtheme</a>.</p>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>